# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

archive_metadata <- function(path) {
    .Call(`_casen_archive_metadata`, path)
}

archive_filters <- function() {
    .Call(`_casen_archive_filters`)
}

archive_formats <- function() {
    .Call(`_casen_archive_formats`)
}

libarchive_version_ <- function() {
    .Call(`_casen_libarchive_version_`)
}

archive_extract_ <- function(archive_filename, filenames, sz = 16384L) {
    invisible(.Call(`_casen_archive_extract_`, archive_filename, filenames, sz))
}

read_connection <- function(archive_filename, filename, mode, format, filters, sz = 16384L) {
    .Call(`_casen_read_connection`, archive_filename, filename, mode, format, filters, sz)
}

